// <auto-generated />
using BackEnd_SolucionesInterPaisa.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd_SolucionesInterPaisa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230411000633_primerMigracion")]
    partial class primerMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEnd_SolucionesInterPaisa.Models.RoutersFichas", b =>
                {
                    b.Property<int>("idMikrotik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoardName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentFirmware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryFirmware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmwareType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Routerboard")
                        .HasColumnType("bit");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpgradeFirmware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionIPMKT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estadoMKT")
                        .HasColumnType("bit");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<string>("ordenMKT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordIPMKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioIPMKT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMikrotik");

                    b.ToTable("RoutersFichas");
                });

            modelBuilder.Entity("BackEnd_SolucionesInterPaisa.Models.UsuariosCreadosHotspot", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LongitudUserFichas")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("bytesIn")
                        .HasColumnType("bigint");

                    b.Property<long>("bytesOut")
                        .HasColumnType("bigint");

                    b.Property<string>("cantidadfichas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("disabled")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_Mikrotik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id_vendedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("limitBytesIn")
                        .HasColumnType("bigint");

                    b.Property<long>("limitBytesOut")
                        .HasColumnType("bigint");

                    b.Property<int>("limitBytesTotal")
                        .HasColumnType("int");

                    b.Property<string>("limitUptime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("macAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("packetsIn")
                        .HasColumnType("bigint");

                    b.Property<long>("packetsOut")
                        .HasColumnType("bigint");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planesFichas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prefijoFichas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("routes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("server")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("servidorHotspot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoInicioDeSesionFichas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoPasswordGenerarFichas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoUsuarioGenerarFichas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uptime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("valorLongPassFichas")
                        .HasColumnType("int");

                    b.Property<string>("vendedorFichas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UsuariosCreadosHotspot");
                });
#pragma warning restore 612, 618
        }
    }
}
